### ISSUE TITLE
[Bug]: Disabled fields that have values, are considered unfilled when submitting

### ISSUE THREAD

**Issue by dan-cooke** [airjp73/remix-validated-form#157]
### Which packages are impacted?

- [X] `remix-validated-form`
- [X] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

```json
"@remix-validated-form/with-zod": "^2.0.1",
"zod-form-data": "^1.2.0",
"remix-validated-form": "^4.5.1"
```

### Please provide a link to a minimal reproduction of the issue.

https://codesandbox.io/s/github/airjp73/remix-validated-form/tree/main/apps/bug-repro

## TODO: repro
I will upddate the repro soon, just reporting incase you were immediately aware of this issue @airjp73 

1. Given the following zod schema
```ts
export const AccountSchema = zfd.formData({
  username: zfd.text(),
  password: zfd.text(
    z
      .string()
      .min(6, `The pincode should be 6 digits long`)
      .max(6, `The pincode should be 6 digits long`)
      .regex(/\d{6}/, `Invalid pincode. Only numbers are allowed`),
  ),
  assignedDevice: zfd.text(z.string()),
});
```
2.  Using it simply like

```.ts
<ValidatedForm validator={AccountValidator} >
    <input name='username'/>
    <input name='password'/>
    <select name='assignedDevice' />
</ValidatedForm>
```

Works as expected, ie.

> Validation is applied to all the fields, I am unable to submit without filling in username/ password + picking a device

3. However, repurposing this same form/validator on a screen that allows my users to edit **only** the device, but allows them to **view** the username/ password has an issue.

In this new screen, i modify the original form to **disable** the 2 text inputs

```diff
- <ValidatedForm validator={AccountValidator} >
+ <ValidatedForm validator={AccountValidator} defaultValues={userFromApi} >
-     <input name='username'/>
+    <input name='username' disabled={isEditScreen} />
-     <input name='password'/>
+    <input name='password' disabled={isEditScreen} />
    <select name='assignedDevice' />
</ValidatedForm>
```

## Actual behaviour
This results in a "Required" error below both of the disabled inputs
<img width="479" alt="image" src="https://user-images.githubusercontent.com/22816887/184625495-3425ca67-0f6a-40c8-adb7-5ff432d27367.png">

### Expected behavior

The form should "see" the 2 disabled values, without having to make them enabled.

### Platform

- OS: MacOs
- Browser: Chrome
- Version:

**Comment by airjp73** [comment]
Beehive it it not, this is actually the expected behavior of the `disabled` prop.

[MDN reference] (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#disabled)
> Specifically, disabled inputs do not receive the click event, and **disabled inputs are not submitted with the form.**

Disabled inputs are not submitted, but `readOnly` inputs are. If you use that instead, you might match your expected behavior better.

[MDN read-only](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#readonly)

Alternatively, if you need to use `disabled`, you could use hidden inputs to provide the values of those fields, or you could modify your scheme to not expect them.

**Comment by dan-cooke** [comment]
@airjp73 ah wow maybe I should brush up on my HTML forms.

I just decided to omit them from my scheme on the new screen as you suggested.

thanks!

**Comment by airjp73** [comment]
That's one of the cool things about Remix. I didn't know this either, before I started using Remix.
