### ISSUE TITLE
[Bug]: import.meta on Cloudlfare still not working (see #89)

### ISSUE THREAD

**Issue by saibotrellum** [airjp73/remix-validated-form#264]
### Which packages are impacted?

- [x] `remix-validated-form`
- [x] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

As @jamesarosen in #89 said, I can confirm import.meta, called by zustand, still throws the error described in #89 on cloudflare pages.
See [James' comment](https://github.com/airjp73/remix-validated-form/issues/89#issuecomment-1442477374) for details. Ignoring slight version changes, same goes here.

Only zustand uses import.meta (says search through ./build), and npm explain zustand says 

zustand@4.3.6
node_modules/zustand
  zustand@"^4.3.0" from  #remix-validated-form@4.6.10
  node_modules/remix-validated-form
    remix-validated-form@"^4.6.10" from the root project
    peer remix-validated-form@"^4.x" from @remix-validated-form/with-zod@2.0.5
    node_modules/@remix-validated-form/with-zod
      @remix-validated-form/with-zod@"^2.0.5" from the root project

### Please provide a link to a minimal reproduction of the issue.

https://github.com/omarkhatibco/remix-cf-remix-validated-form

### Steps to Reproduce the Bug or Issue

npm run dev

### Expected behavior

Not show errors on popular development platform

### Platform

Cloudflare Local Wrangler

**Comment by sa23sa** [comment]
> I noticed there's a [solution given in the zustand repo](https://github.com/pmndrs/zustand/issues/1639#issuecomment-1431653245) for this issue. Does that fix the issue for you?

I had the same issue and now It's working thanks.

**Comment by airjp73** [comment]
I'm going to close this issue now as it seems like we have a working solution.
