### ISSUE TITLE
[Bug]: Remix on Cloudflare Worker - Cannot use 'import.meta' outside a module

### ISSUE THREAD

**Issue by omarkhatibco** [airjp73/remix-validated-form#89]
### Which packages are impacted?

- [X] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

 - `remix-validated-form`: ^4.1.9
 - `@remix-validated-form/with-zod`: ^2.0.1

### Please provide a link to a minimal reproduction of the issue.

https://github.com/omarkhatibco/remix-cf-remix-validated-form

### Steps to Reproduce the Bug or Issue

just run `yarn dev`

### Expected behavior

should work fine.

### Platform

- OS: mac
- Browser: chrome
- Version: 100

### Additional context

this Problem is not related directly to `remix-validated-form` it's related more to `Jotai`, but since I could not find anyway to fix `Jotai`, I had to report it. 

the possible solution is just change the import from 

```diff
- import { useUpdateAtom } from 'jotai/utils'
+ import { useUpdateAtom } from 'jotai/utils.cjs'
```

reference for the [Issue](https://github.com/pmndrs/jotai/issues/281)

**Comment by airjp73** [comment]
Thanks for bringing this up! I think this would be good to fix.

**Comment by omarkhatibco** [comment]
Hello @airjp73,
it seems that v1.3.5 is [breaking ESM](https://github.com/remix-run/remix/issues/2691) in Remix, let's wait till v1.3.6 and check it again.

**Comment by acusti** [comment]
@aiji42 and @omarkhatibco thanks for debugging this! your comments and links allowed me to understand / track down what was going on for me. i’m using jotai with remix and cloudflare-workers and ran into the same problem, but i couldn’t find any open issues related to it in remix-run/remix or pmndrs/jotai, though there is a closed issue in the jotai repo: https://github.com/pmndrs/jotai/issues/1094

do either of you know where i can look to follow along with potential future progress with this?

also, as an aside, i was able to get things working for myself by pinning `jotai` to v1.5.3 (v1.6.0 introduced the `import.meta.env` checks via the [rollup.config.js](https://github.com/pmndrs/jotai/blob/9d0a920c1b52ebddf19ad470f017b1b41cf08a50/rollup.config.js#L62)).

**Comment by airjp73** [comment]
Is this still an issue in the latest version? I migrated all the state management to `zustand` awhile back -- does it have the same problem?

**Comment by airjp73** [comment]
Going to close this. Please feel free to re-open or write a new issue if the problem persists with the latest version.

**Comment by jamesarosen** [comment]
This is still an issue with
```
remix-validated-form 4.6.9
@remix-validated-form/with-zod 2.0.5
@remix-run/cloudflare 1.13.0
@remix-run/cloudflare-pages 1.13.0
@remix-run/server-runtime 1.13.0
```
but only with `"target": "ES2019"` in `tsconfig.json`. That's the default for the Remix-Cloudflare template.
